# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EiVVqUqSj9H4vd3kaLYwi9GdKgQGpgmw
"""

lista = [3,4,8,6,3,5]
for n in lista:
  print(n)

for n in range (1,201):
  print(n)

menino = {
  'key': 'value',
  'nome': 'Carlos',
  'idade': 17,
  'cidade': 'guarulhos'
}
for chave, valor in menino.items():
  print(chave, ':', valor)

matriz = [[1,2,3], [4,5,6], [7,8,9]]
for linha in matriz:
  for elemento in linha:
    print(elemento)

# Exercício 1: Escreva um programa que use a função range() para gerar os números pares de 2 a 20 e, em seguida, imprima cada número.

for i in range(2,21,2):
  print(i)

# Exercício 2: Escreva um programa que use a função range() para gerar os múltiplos de 5 em 5 a 50 e, em seguida, calcule e imprima a soma desses múltiplos.
for i in range(5,51,5):
  soma=sum(range(5,51,5))
  print(soma)

# Exercício 3: Escreva um programa que use a função type() para verificar o tipo de uma variável.
x = ['g','h','i','j','k']
y = 45
z = {'nome': 'Carlos'}
print('var x =', type(x), 'var y =', type(y), 'var z =', type(z))

# Exercício 4: Escreva um programa que use a função print() para imprimir uma mensagem de saudação personalizada, incluindo o nome do usuário.
name = str(input('Insira o seu nome: '))
print('Olá', name,)

# Exercício 5: Escreva um programa que use a função range() para gerar os números ímpares de 1 a 10 e, em seguida, calcule e imprima a média desses números.
for i in range (1,11):
  if i%2!=0:
    print(i)
soma = (sum(range(1,11)))
print(soma)

soma = sum(range(5,51,5))
print(soma)
